// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrxtnmktqsuwgpkvemgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyeHRubWt0cXN1d2dwa3ZlbWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDA5NzEsImV4cCI6MjA3MzUxNjk3MX0.0Aui1zGPnXcfP-n_xYGARlny07gRCY_sICZYk_nzbqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});